from catppuccin import Flavour

BLOCK_SIZE = 40
HEIGHT = 20
WIDTH = 30
WIN_HEIGHT = BLOCK_SIZE*HEIGHT
WIN_WIDTH = BLOCK_SIZE*WIDTH

PALETTE = Flavour.frappe()
BACKGROUND_COLOR = PALETTE.crust.rgb
SNAKE_COLOR_LIGHT = PALETTE.green.rgb
SNAKE_COLOR_DARK = PALETTE.blue.rgb
FRUIT_COLOR = PALETTE.red.rgb
TEXT_COLOR = PALETTE.text.rgba

FONT = "JetBrainsMono Nerd Font"

